CREATE TABLE [dbo].[TBTESTE]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [NOME] VARCHAR(100) NOT NULL, 
    [DATAGERACAO] DATETIME NOT NULL, 
    [IDMATERIA] INT NOT NULL, 
    CONSTRAINT [FK_TBTESTE_ToTBMATERIA_ID] FOREIGN KEY ([IDMATERIA]) REFERENCES [TBMATERIA]([ID])
)
