CREATE TABLE [dbo].[TBTESTEQUESTOES]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [IDQUESTAO] INT NOT NULL, 
    [IDTESTE] INT NOT NULL, 
	[POSICAONOTESTE] INT NOT NULL,
    CONSTRAINT [FK_TBTESTEQUESTOES_ToTBQUESTAO_ID] FOREIGN KEY ([IDQUESTAO]) REFERENCES [TBQUESTAO]([ID]), 
    CONSTRAINT [FK_TBTESTEQUESTOES_ToTBTESTE_ID] FOREIGN KEY ([IDTESTE]) REFERENCES [TBTESTE]([ID])
)