CREATE TABLE [dbo].[TBALTERNATIVA]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [ENUNCIADO] VARCHAR(100) NOT NULL, 
    [CORRETA] BIT NOT NULL, 
    [LETRA] CHAR NOT NULL,
    [IDQUESTAO] INT NOT NULL, 
    CONSTRAINT [FK_TBALTERNATIVA_ToTBQUESTAO_ID] FOREIGN KEY ([IDQUESTAO]) REFERENCES [TBQUESTAO]([ID])
)
