CREATE TABLE [dbo].[TBQUESTAO]
(
	[Id] INT NOT NULL PRIMARY KEY, 
    [ENUNCIADO] VARCHAR(100) NOT NULL, 
    [BIMESTRE] INT NOT NULL, 
    [IDMATERIA] INT NOT NULL, 
    [IDALTERNATIVACORRETA] INT NOT NULL, 
    CONSTRAINT [FK_TBQUESTAO_ToTBMATERIA_ID] FOREIGN KEY ([IDMATERIA]) REFERENCES [TBMATERIA]([Id]), 
    CONSTRAINT [FK_TBQUESTAO_ToTBALTERNATIVA_ID] FOREIGN KEY ([IDALTERNATIVACORRETA]) REFERENCES [TBALTERNATIVA]([ID])
)
