CREATE TABLE [dbo].[TBQUESTAO]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [ENUNCIADO] VARCHAR(100) NOT NULL, 
    [BIMESTRE] INT NOT NULL, 
    [IDMATERIA] INT NOT NULL, 
    CONSTRAINT [FK_TBQUESTAO_ToTBMATERIA_ID] FOREIGN KEY ([IDMATERIA]) REFERENCES [TBMATERIA]([Id])
)
