// <auto-generated />
namespace ws_banco_tabajara.Infra.ORM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class migrationsAdicionandoOnDeleteCascadeParaCliente : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migrationsAdicionandoOnDeleteCascadeParaCliente));
        
        string IMigrationMetadata.Id
        {
            get { return "201807271806427_migrationsAdicionandoOnDeleteCascadeParaCliente"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
